<?php
$eta_title = 'Israel ETA-IL Entry Requirements | D.A.K Travel';
$eta_desc  = 'Official ETA-IL guidance for travellers to Israel, including who generally needs an ETA-IL, exemptions and the official PIBA application link.';
add_filter( 'daktravel_seo_defaults', static function ( $defaults ) use ( $eta_title, $eta_desc ) { $defaults['israel-eta-il-entry-requirements'] = array( 'title' => $eta_title, 'description' => $eta_desc ); return $defaults; } );
if ( defined( 'RANK_MATH_VERSION' ) ) { add_filter( 'rank_math/frontend/title', static function () use ( $eta_title ) { return $eta_title; } ); add_filter( 'rank_math/frontend/description', static function () use ( $eta_desc ) { return $eta_desc; } ); }
get_header();
?>
<main>
<section class="dak-page-hero"><div class="container dak-page-hero-grid"><div class="dak-page-hero-copy"><div class="eyebrow">Israel entry requirement</div><h1>ETA-IL and entry requirements for travel to Israel.</h1><p class="lead">Before travelling to Israel on a foreign passport, check whether you need an ETA-IL electronic travel authorisation or an Israeli visa.</p><div class="dak-page-actions"><a class="btn btn--primary" target="_blank" rel="noopener noreferrer" href="https://israel-entry.piba.gov.il/">Official ETA-IL website</a><a class="btn btn--whatsapp" target="_blank" rel="noopener noreferrer" href="<?php echo esc_url( daktravel_whatsapp_url( 'Good day D.A.K Travel. Please help me check the entry requirements for my trip to Israel.' ) ); ?>">WhatsApp D.A.K</a></div></div><?php echo wp_kses_post( daktravel_media_slot( 'daktravel_israel_image', 'Tel Aviv, Israel', 'Israel entry information', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Azriely_Center.jpg' ) ); ?></div></section>
<section class="dak-intro-section"><div class="container dak-narrow"><div class="eyebrow">Who needs ETA-IL?</div><h2>Visa-exempt foreign travellers generally need an ETA-IL before departure.</h2><p class="lead">Since 1 January 2025, travellers from visa-exempt countries generally need an approved ETA-IL before travelling to Israel. Travellers who require a visa must obtain the appropriate visa instead.</p><div class="dak-feature-list"><div class="dak-feature-row"><span class="num">01</span><strong>Visa-exempt passport holders</strong><p>Check eligibility and apply for ETA-IL before travel using the official Population and Immigration Authority website.</p></div><div class="dak-feature-row"><span class="num">02</span><strong>Israeli citizens and certain Israeli-status holders</strong><p>Israeli citizens and some holders of Israeli documents or status may be exempt from ETA-IL. Use the official eligibility guidance for your exact circumstances.</p></div><div class="dak-feature-row"><span class="num">03</span><strong>Visa-required nationals</strong><p>ETA-IL does not replace a visa. If your nationality requires an Israeli visa, follow the relevant Israeli consular process.</p></div><div class="dak-feature-row"><span class="num">04</span><strong>Apply only on the official site</strong><p>Use the Israeli government PIBA website and avoid unofficial third-party application sites.</p></div></div></div></section>
<section class="section section--ivory"><div class="container editorial-split"><div><div class="eyebrow">Official source</div><h2>Check the rule for the passport you will actually travel on.</h2><p class="lead">Entry requirements depend on nationality, passport type, Israeli status and purpose of travel. D.A.K can help with your flight booking, but the Israeli authorities make the final decision on entry.</p></div><div class="editorial-panel"><div class="case-study-label">Official Israel government</div><h3>PIBA Israel Entry</h3><p>Use the official portal to check ETA-IL eligibility, apply and review current information.</p><a class="btn btn--primary" target="_blank" rel="noopener noreferrer" href="https://israel-entry.piba.gov.il/">Go to official Israel Entry portal</a></div></div></section>
<section class="dak-quiet-cta"><div class="container dak-quiet-cta-inner"><div><div class="eyebrow">Planning Israel travel?</div><h2>Send us your dates and passport nationality.</h2><p>We can help with the travel arrangements and point you to the official entry source that applies to your journey.</p></div><div class="dak-page-actions"><a class="btn btn--outline" href="<?php echo esc_url( home_url('/israel-travel/') ); ?>">Israel Travel Desk</a><a class="btn btn--whatsapp" target="_blank" rel="noopener noreferrer" href="<?php echo esc_url( daktravel_whatsapp_url( 'Good day D.A.K Travel. Please assist me with travel to Israel.' ) ); ?>">WhatsApp Us</a></div></div></section>
</main>
<?php get_footer(); ?>