<?php get_header(); ?>
<main>
<section class="section section--ivory"><div class="container editorial-split"><div><div class="eyebrow">Contact D.A.K Travel</div><h1>Send us your travel details.</h1><p class="lead">WhatsApp is best for quick enquiries, dates and screenshots. Use the form below for longer requests, group lists and formal quotations.</p><div class="hero-actions"><a class="btn btn--whatsapp" href="<?php echo esc_url( daktravel_whatsapp_url( 'Good day D.A.K Travel. I would like assistance with a travel enquiry.' ) ); ?>">WhatsApp +27 82 440 6144</a></div><p><strong>Telephone:</strong> <a href="tel:+27114405980">+27 11 440 5980</a></p></div><div class="editorial-panel"><div class="case-study-label">For a faster reply</div><h3>Please include:</h3><p>Departure city · destination · travel dates · number of travellers · preferred cabin · any special requirements.</p><p><strong>Confidentiality:</strong> your enquiry is handled by the D.A.K team and used to assist with your travel request.</p></div></div></section>
<section class="section" id="enquiry"><div class="container utility-page-shell"><div class="section-intro"><div class="eyebrow">Email enquiry</div><h2>Tell us what you need.</h2><p class="lead">Complete the form and it will be emailed directly to D.A.K Travel.</p></div>
<?php if ( isset( $_GET['sent'] ) && '1' === sanitize_text_field( wp_unslash( $_GET['sent'] ) ) ) : ?><div class="form-message form-message--success">Thank you. Your enquiry has been sent to D.A.K Travel.</div><?php elseif ( isset( $_GET['sent'] ) && in_array( sanitize_text_field( wp_unslash( $_GET['sent'] ) ), array( '0', 'error' ), true ) ) : ?><div class="form-message form-message--error">We could not send your enquiry. Please check the required fields or WhatsApp us instead.</div><?php endif; ?>
<form class="dak-enquiry-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
<input type="hidden" name="action" value="daktravel_enquiry">
<?php wp_nonce_field( 'daktravel_enquiry', 'daktravel_enquiry_nonce' ); ?>
<div class="dak-honeypot" aria-hidden="true"><label>Website<input type="text" name="website" tabindex="-1" autocomplete="off"></label></div>
<div class="form-grid"><label>Full name<span>*</span><input type="text" name="name" required autocomplete="name"></label><label>Email<span>*</span><input type="email" name="email" required autocomplete="email"></label><label>Mobile / WhatsApp<input type="tel" name="mobile" autocomplete="tel"></label><label>Enquiry type<select name="enquiry_type"><option value="Israel travel">Israel travel</option><option value="Group or delegation">Group or delegation</option><option value="Business travel">Business travel</option><option value="Complex personal travel">Complex personal travel</option><option value="Existing booking">Existing booking</option><option value="General travel enquiry">General travel enquiry</option></select></label><label>Departure city<input type="text" name="departure"></label><label>Destination<input type="text" name="destination"></label><label>Travel dates<input type="text" name="dates" placeholder="e.g. 12–20 October 2026"></label><label>Number of travellers<input type="text" name="travellers"></label></div>
<label class="form-full">Tell us what you need<span>*</span><textarea name="message" rows="6" required></textarea></label>
<div class="form-submit"><button class="btn btn--primary" type="submit">Send Enquiry</button><span>Your message is sent directly to D.A.K Travel.</span></div>
</form>
</div></section>
</main><?php get_footer(); ?>