<?php
$south_africa_hero_images = array(
    array( 'url' => 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Cape_Town_Table_Mountain.jpg', 'alt' => 'קייפטאון והר השולחן בדרום אפריקה' ),
    array( 'url' => 'https://images.pexels.com/photos/6624568/pexels-photo-6624568.jpeg?auto=compress&cs=tinysrgb&w=1600', 'alt' => 'קו החוף של קייפטאון בדרום אפריקה' ),
    array( 'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/22/South_Africa_-_Drakensberg_%2816261357780%29.jpg', 'alt' => 'הרי דרקנסברג בדרום אפריקה' ),
    array( 'url' => 'https://upload.wikimedia.org/wikipedia/commons/a/a2/View_over_Vaal_Dam.jpg', 'alt' => 'סכר ואל בדרום אפריקה' ),
    array( 'url' => 'https://images.pexels.com/photos/34166928/pexels-photo-34166928.jpeg?auto=compress&cs=tinysrgb&w=1600', 'alt' => 'קניון בלייד ריבר בדרום אפריקה' ),
    array( 'url' => 'https://images.pexels.com/photos/33621915/pexels-photo-33621915.jpeg?auto=compress&cs=tinysrgb&w=1600', 'alt' => 'פיל בשמורת טבע בדרום אפריקה' ),
);
?>
<section class="dak-page-hero"><div class="container dak-page-hero-grid"><div class="dak-page-hero-copy"><div class="eyebrow">ישראל → דרום אפריקה</div><h1>טיסות מישראל לדרום אפריקה, יוהנסבורג, קייפטאון ויעדים נוספים.</h1><p class="lead">אנחנו מסייעים לנוסעים היוצאים מישראל להשוות טיסות מתל אביב ומנמל התעופה בן גוריון לדרום אפריקה, כולל טיסות המשך בתוך המדינה.</p><div class="dak-page-actions"><a class="btn btn--whatsapp" target="_blank" rel="noopener noreferrer" href="<?php echo esc_url( daktravel_whatsapp_url( 'שלום D.A.K Travel. אשמח לעזרה עם טיסה מישראל לדרום אפריקה.' ) ); ?>">WhatsApp</a><a class="btn btn--outline" href="<?php echo esc_url( daktravel_native_hebrew_url( 'contact' ) ); ?>#enquiry">שליחת תאריכים</a></div></div><figure class="dak-media-slot has-image dak-route-slideshow-frame"><div class="dak-route-slideshow dak-route-slideshow--6" aria-hidden="true"><?php foreach ( $south_africa_hero_images as $index => $image ) : ?><span class="dak-route-slide dak-route-slide--<?php echo esc_attr( $index + 1 ); ?>"><img class="dak-media-image" src="<?php echo esc_url( $image['url'] ); ?>" alt="<?php echo esc_attr( $image['alt'] ); ?>" <?php echo 0 === $index ? 'loading="eager" fetchpriority="high"' : 'loading="lazy"'; ?> decoding="async"></span><?php endforeach; ?></div></figure></div></section>
<section class="dak-intro-section"><div class="container dak-narrow"><div class="eyebrow">מתל אביב לדרום אפריקה</div><h2>אנחנו מסתכלים מעבר לטיסה הראשונה שמופיעה במסך.</h2><p class="lead">המסלול המתאים תלוי בתאריך, זמינות, זמן קונקשן, כבודה, תנאי הכרטיס והיעד הסופי בדרום אפריקה.</p><div class="dak-feature-list"><div class="dak-feature-row"><span class="num">01</span><strong>יוהנסבורג</strong><p>השוואת אפשרויות נוחות והבנת זמני הקונקשן ותנאי הכרטיס.</p></div><div class="dak-feature-row"><span class="num">02</span><strong>קייפטאון ודרבן</strong><p>בדיקת טיסות המשך כאשר היעד הסופי אינו יוהנסבורג.</p></div><div class="dak-feature-row"><span class="num">03</span><strong>כבודה וקונקשנים</strong><p>בדיקה איך הכבודה מטופלת ומה המשמעות של כרטיס אחד לעומת כרטיסים נפרדים.</p></div><div class="dak-feature-row"><span class="num">04</span><strong>שינויים וגמישות</strong><p>כאשר תוכניות משתנות, יש לכם איש קשר שמכיר את המסלול.</p></div></div></div></section>
<section class="section section--ivory"><div class="container editorial-split"><div><div class="eyebrow">המשך בתוך דרום אפריקה</div><h2>יוהנסבורג לא תמיד היא סוף הדרך.</h2><p class="lead">אם ממשיכים לקייפטאון, דרבן, ג׳ורג׳ או עיר אזורית אחרת, כדאי לתכנן את החיבור המקומי יחד עם הטיסה הבינלאומית.</p></div><div class="editorial-panel"><div class="case-study-label">מה חשוב לבדוק</div><h3>כל המסלול, לא רק המחיר.</h3><p>זמן קונקשן · כבודה · מבנה הכרטיס · גמישות · היעד הסופי</p></div></div></section>