<?php
$title = 'עזרה עם הזמנה קיימת | D.A.K Travel';
add_filter( 'pre_get_document_title', static function () use ( $title ) { return $title; }, 9999 );
get_header( 'hebrew-path' );
$sent = isset( $_GET['sent'] ) ? sanitize_text_field( wp_unslash( $_GET['sent'] ) ) : '';
?>
<main>
<section class="dak-page-hero contact-page-hero"><div class="container dak-page-hero-grid"><div class="dak-page-hero-copy"><div class="eyebrow">הזמנה קיימת</div><h1>צריכים עזרה עם הזמנה קיימת?</h1><p class="lead">שלחו לנו את מספר ההזמנה או ה-PNR, שם המשפחה של הנוסע ומה צריך לבדוק או לשנות.</p><div class="dak-page-actions"><a class="btn btn--whatsapp" target="_blank" rel="noopener noreferrer" href="<?php echo esc_url( daktravel_whatsapp_url( 'שלום D.A.K Travel. אשמח לעזרה עם הזמנה קיימת.' ) ); ?>">WhatsApp</a><a class="btn btn--outline" href="#enquiry">שליחת פרטי ההזמנה</a></div></div><?php echo wp_kses_post( daktravel_media_slot( 'daktravel_contact_image', 'כנף מטוס מעל העננים', 'שירות להזמנה קיימת', 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&fm=jpg&q=82&w=1800' ) ); ?></div></section>
<section class="dak-intro-section" id="enquiry"><div class="container utility-page-shell"><div class="eyebrow">טיפול בהזמנה קיימת</div><?php if ( '1' === $sent ) : ?><div class="form-message form-message--success">תודה. הפנייה שלכם נשלחה ל-D.A.K Travel.</div><?php elseif ( 'invalid' === $sent ) : ?><div class="form-message form-message--error">נא למלא שם, כתובת דוא״ל תקינה והודעה.</div><?php elseif ( '0' === $sent ) : ?><div class="form-message form-message--error">לא הצלחנו לשלוח את הפנייה. נסו שוב או פנו אלינו ב-WhatsApp.</div><?php endif; ?><form class="dak-enquiry-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="daktravel_enquiry"><input type="hidden" name="daktravel_enquiry_submit" value="1"><input type="hidden" name="return_type" value="existing"><input type="hidden" name="return_lang" value="he"><input type="hidden" name="enquiry_type" value="Existing booking"><?php wp_nonce_field( 'daktravel_enquiry', 'daktravel_enquiry_nonce' ); ?><div class="dak-honeypot" aria-hidden="true"><label>Website<input type="text" name="website" tabindex="-1" autocomplete="off"></label></div><div class="form-grid"><label>שם מלא<span>*</span><input type="text" name="name" required autocomplete="name"></label><label>דוא״ל<span>*</span><input type="email" name="email" required autocomplete="email"></label><label>טלפון / WhatsApp<input type="tel" name="mobile" autocomplete="tel"></label><label>מספר הזמנה / PNR<input type="text" name="booking_ref"></label><label>שם משפחה של הנוסע<input type="text" name="passenger_surname"></label></div><label class="form-full">מה צריך לבדוק או לשנות?<span>*</span><textarea name="message" rows="5" required></textarea></label><div class="form-submit"><button class="btn btn--primary" type="submit">שליחת פנייה</button><span>הפנייה נשלחת ישירות ל-D.A.K Travel.</span></div></form></div></section>
</main>
<?php get_footer( 'hebrew-path' ); ?>